source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!



target 'XBChatModule' do
  pod "XBChatModule", :path => "../"
end

target 'Tests' do
  pod "XBChatModule", :path => "../"

  pod 'FBSnapshotTestCase'
end
